import mercedesImage from "@/assets/rafilla-mercedes.jpg";
import techBundleImage from "@/assets/rafilla-tech-bundle.jpg";
import apartmentImage from "@/assets/rafilla-apartment.jpg";

export type CompetitionStatus = "LIVE" | "CLOSING SOON" | "UPCOMING" | "COMPLETED";

export type Competition = {
  slug: string;
  title: string;
  category: string;
  partner: string;
  description: string;
  prizeValueKobo: number;
  entryPrice: number;
  totalEntries: number;
  entriesSold: number;
  closes: string;
  daysUntilClose: number;
  status: CompetitionStatus;
  featured?: boolean;
  image: string;
  imageAlt: string;
  accent: "coral" | "sky" | "lemon" | "mint" | "lilac";
  specs: string[];
  drawDate: string;
  prizeCondition: string;
  warranty: string;
  make: string;
  model: string;
  year: number | string;
  serialNo: string;
  dimensions: string;
  color: string;
  inclusions: string[];
  exclusions: string[];
  maxTicketsPerUser: number;
  marketValueKobo: number;
};

export const categories = [
  "All",
  "Vehicles",
  "Electronics",
  "Homes",
  "Fashion",
  "Jewelry",
  "Business grants",
  "Lifestyle",
  "Collectibles",
];

export const partners = [
  "Lekki Luxury Autos",
  "Nova Electronics",
  "Abeokuta Homes",
  "Lagos Jewels Co.",
  "Abuja Fashion Hub",
];

export const prizeTiers = ["Bronze", "Silver", "Gold", "Platinum", "Diamond"];

const accents: Competition["accent"][] = ["coral", "sky", "lemon", "mint", "lilac"];

const mk = (n: number) => n * 100;

export const competitions: Competition[] = [
  {
    slug: "mercedes-benz-c-class",
    title: "Mercedes-Benz C-Class 2025",
    category: "Vehicles",
    partner: "Lekki Luxury Autos",
    description:
      "A refined executive sedan with a premium cabin, intelligent assistance, and the presence to make every arrival count. Experience the perfect balance of luxury, performance, and cutting-edge technology in this iconic German-engineered masterpiece.",
    prizeValueKobo: mk(12_000_000),
    entryPrice: mk(10_000),
    totalEntries: 5_000,
    entriesSold: 4_210,
    closes: "18 Oct · 23:59",
    daysUntilClose: 13,
    status: "LIVE",
    featured: true,
    image: mercedesImage,
    imageAlt: "Silver Mercedes-Benz C-Class sedan in a warm lilac studio",
    accent: "coral",
    specs: ["2025 model", "Premium interior", "Automatic transmission", "Executive sedan", "Leather seats", "Panoramic sunroof", "360° camera"],
    drawDate: "Fri 3 Oct 2026 · 6:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "1-yr manufacturer warranty",
    make: "Mercedes-Benz",
    model: "C-Class C300",
    year: 2025,
    serialNo: "MB-C300-2025-78421",
    dimensions: "4751 x 1820 x 1437 mm",
    color: "High-Tech Silver Metallic",
    inclusions: ["Full service package", "Comprehensive insurance (1yr)", "Custom floor mats", "Delivery to Lagos/OG"],
    exclusions: ["Fuel costs", "Driver", "Registration beyond first year"],
    maxTicketsPerUser: 50,
    marketValueKobo: mk(12_500_000),
  },
  {
    slug: "nova-x1-bundle",
    title: "Nova X1 Ultimate Tech Bundle",
    category: "Electronics",
    partner: "Nova Electronics",
    description:
      "A complete everyday tech set built around a flagship smartphone and connected essentials. Power through your day with seamless integration across all your devices — phone, audio, wearables, and home.",
    prizeValueKobo: mk(1_950_000),
    entryPrice: mk(5_000),
    totalEntries: 10_000,
    entriesSold: 9_870,
    closes: "5 Oct · 23:59",
    daysUntilClose: 0,
    status: "CLOSING SOON",
    image: techBundleImage,
    imageAlt: "Blue smartphone, earbuds, and mint smartwatch on a pastel desk",
    accent: "sky",
    specs: ["Flagship smartphone", "Wireless earbuds", "Smartwatch", "Premium accessory set", "Tablet", "Wireless charger"],
    drawDate: "Mon 8 Sep 2026 · 4:00 PM WAT",
    prizeCondition: "Brand new, sealed",
    warranty: "1-yr manufacturer warranty",
    make: "Nova",
    model: "X1 Ultimate Collection",
    year: 2026,
    serialNo: "NV-X1B-2026-33921",
    dimensions: "Phone: 160.8 x 76.4 x 8.2 mm",
    color: "Ocean Blue / Midnight Black",
    inclusions: ["Smartphone 256GB", "Pro wireless earbuds", "Smartwatch GPS", "11\" WiFi tablet", "65W GaN charger", "MagSafe accessories"],
    exclusions: ["Subscription services", "Extended warranty", "Replacement beyond warranty"],
    maxTicketsPerUser: 100,
    marketValueKobo: mk(2_100_000),
  },
  {
    slug: "luxury-2-bed-apartment",
    title: "Luxury 2-Bed Apartment — Lekki",
    category: "Homes",
    partner: "Abeokuta Homes",
    description:
      "A bright contemporary apartment designed for calm city living, entertaining, and everyday comfort. Located in the heart of Lekki Phase 1 with stunning lagoon views, premium finishes, and world-class amenities.",
    prizeValueKobo: mk(38_000_000),
    entryPrice: mk(2_500),
    totalEntries: 22_500,
    entriesSold: 9_200,
    closes: "30 Nov · 23:59",
    daysUntilClose: 56,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Bright contemporary apartment lounge with warm daylight and yellow accents",
    accent: "lemon",
    specs: [
      "Two bedrooms",
      "Contemporary lounge",
      "Daylight-filled interiors",
      "City-facing balcony",
      "Fitted kitchen",
      "Serviced building",
      "Swimming pool",
    ],
    drawDate: "Mon 1 Dec 2026 · 6:00 PM WAT",
    prizeCondition: "Brand new, fully finished",
    warranty: "Developer defect warranty (2yr)",
    make: "Abeokuta Homes Ltd",
    model: "Lekki Residences — Type B2",
    year: 2026,
    serialNo: "AH-LR2-B2-1404",
    dimensions: "85 sqm (net internal area)",
    color: "Cream / Timber accents",
    inclusions: ["Fitted kitchen appliances", "Split-unit ACs (all rooms)", "Wardrobes fitted", "Generator backup shared", "Gym membership (1yr)"],
    exclusions: ["Service charge after 1yr", "Personal furniture", "Utility bills"],
    maxTicketsPerUser: 200,
    marketValueKobo: mk(40_000_000),
  },
  {
    slug: "range-rover-sport-2026",
    title: "Range Rover Sport 2026",
    category: "Vehicles",
    partner: "Lekki Luxury Autos",
    description:
      "Command the road in the new Range Rover Sport — a masterclass in luxury SUV design with uncompromising capability and head-turning road presence.",
    prizeValueKobo: mk(45_000_000),
    entryPrice: mk(15_000),
    totalEntries: 8_000,
    entriesSold: 3_420,
    closes: "28 Oct · 23:59",
    daysUntilClose: 23,
    status: "LIVE",
    image: mercedesImage,
    imageAlt: "Sleek black Range Rover Sport against modern city backdrop",
    accent: "coral",
    specs: ["2026 model", "Dynamic SE trim", "V6 Twin Turbo", "Terrain Response 2", "Meridian audio", "Heated seats"],
    drawDate: "Fri 31 Oct 2026 · 6:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "3-yr manufacturer warranty",
    make: "Land Rover",
    model: "Range Rover Sport Dynamic SE",
    year: 2026,
    serialNo: "LR-RRS-26-55108",
    dimensions: "4946 x 2047 x 1820 mm",
    color: "Santorini Black",
    inclusions: ["Service plan (5yrs)", "Full insurance (2yrs)", "Privacy glass", "Roof rails", "Delivery nationwide"],
    exclusions: ["Fuel", "Personal driver", "Custom modifications"],
    maxTicketsPerUser: 40,
    marketValueKobo: mk(48_000_000),
  },
  {
    slug: "macbook-pro-studio-setup",
    title: "MacBook Pro M4 Max Studio Setup",
    category: "Electronics",
    partner: "Nova Electronics",
    description:
      "The ultimate creator bundle: M4 Max MacBook Pro paired with Studio Display, premium audio, and every accessory you need for pro-level production.",
    prizeValueKobo: mk(4_200_000),
    entryPrice: mk(7_500),
    totalEntries: 12_000,
    entriesSold: 5_650,
    closes: "15 Oct · 23:59",
    daysUntilClose: 10,
    status: "LIVE",
    image: techBundleImage,
    imageAlt: "Silver MacBook Pro on clean desk with studio display",
    accent: "sky",
    specs: ["MacBook Pro 16\" M4 Max", "Studio Display", "Magic Keyboard", "Magic Trackpad", "AirPods Max", "Pro mic"],
    drawDate: "Mon 20 Oct 2026 · 4:00 PM WAT",
    prizeCondition: "Brand new, sealed",
    warranty: "1-yr AppleCare+ included",
    make: "Apple",
    model: "MacBook Pro M4 Max Bundle",
    year: 2026,
    serialNo: "APL-MBP4M-88201",
    dimensions: "Laptop: 35.57 x 24.81 x 1.68 cm",
    color: "Silver / Space Black",
    inclusions: ["M4 Max 36-core GPU", "64GB Unified Memory", "2TB SSD", "Studio Display Nano", "AirPods Max", "Blue Yeti X"],
    exclusions: ["Software subscriptions", "Custom engraving"],
    maxTicketsPerUser: 80,
    marketValueKobo: mk(4_500_000),
  },
  {
    slug: "3-bed-duplex-ikeja",
    title: "3-Bed Duplex with BQ — Ikeja GRA",
    category: "Homes",
    partner: "Abeokuta Homes",
    description:
      "A magnificent detached duplex in the serene environment of Ikeja GRA. Featuring spacious rooms, a private compound, BQ, modern kitchen, and premium finishes throughout.",
    prizeValueKobo: mk(85_000_000),
    entryPrice: mk(5_000),
    totalEntries: 30_000,
    entriesSold: 12_400,
    closes: "15 Jan · 23:59",
    daysUntilClose: 101,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Luxurious 3-bed duplex exterior with landscaped compound",
    accent: "lemon",
    specs: ["3 bedrooms all ensuite", "BQ with kitchenette", "Private compound", "2-car garage", "CCTV wired", "Solar inverter backup"],
    drawDate: "Wed 21 Jan 2026 · 6:00 PM WAT",
    prizeCondition: "Brand new, fully fitted",
    warranty: "2-yr developer warranty",
    make: "Abeokuta Homes Ltd",
    model: "Ikeja Signature Duplex",
    year: 2026,
    serialNo: "AH-ISD-021",
    dimensions: "450 sqm land · 280 sqm built",
    color: "Textured cream / brown accents",
    inclusions: ["All rooms AC", "Fitted kitchen with island", "Water heater all bathrooms", "Borehole + treatment", "10KW solar system"],
    exclusions: ["Property registration fees", "Annual service charge after 2yrs"],
    maxTicketsPerUser: 500,
    marketValueKobo: mk(90_000_000),
  },
  {
    slug: "designer-wedding-gown",
    title: "Couture Wedding Gown Experience",
    category: "Fashion",
    partner: "Abuja Fashion Hub",
    description:
      "A bespoke couture wedding gown experience with the top designer at Abuja Fashion Hub. Includes 5 fittings, premium lace and silk, and a complimentary reception dress.",
    prizeValueKobo: mk(3_500_000),
    entryPrice: mk(3_500),
    totalEntries: 6_000,
    entriesSold: 2_100,
    closes: "10 Dec · 23:59",
    daysUntilClose: 66,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Exquisite couture wedding gown on mannequin",
    accent: "lilac",
    specs: ["Fully custom couture", "Imported French lace", "5 fittings", "Reception dress included", "Veil & accessories"],
    drawDate: "Sat 13 Dec 2026 · 3:00 PM WAT",
    prizeCondition: "Bespoke, new creation",
    warranty: "Alteration support until wedding",
    make: "Abuja Fashion Hub — Atelier",
    model: "Custom Couture Bridal",
    year: 2026,
    serialNo: "AFH-BC-2026-112",
    dimensions: "Fitted to client",
    color: "Ivory / Champagne / custom",
    inclusions: ["Design consultation", "Fabric selection premium", "5 fitting sessions", "Bridal veil", "Bridesmaid robe gift"],
    exclusions: ["Shoes", "Jewelry", "Hair and makeup"],
    maxTicketsPerUser: 100,
    marketValueKobo: mk(3_800_000),
  },
  {
    slug: "mens-designer-wardrobe",
    title: "Gentleman's Designer Wardrobe Refresh",
    category: "Fashion",
    partner: "Abuja Fashion Hub",
    description:
      "A complete luxury wardrobe refresh featuring bespoke suits, handmade shoes, premium casual wear, and a personal styling session worth ₦500,000.",
    prizeValueKobo: mk(2_800_000),
    entryPrice: mk(3_000),
    totalEntries: 8_000,
    entriesSold: 4_800,
    closes: "22 Oct · 23:59",
    daysUntilClose: 17,
    status: "LIVE",
    image: techBundleImage,
    imageAlt: "Mens luxury suits on rack with leather accessories",
    accent: "mint",
    specs: ["3 bespoke suits", "2 handmade shoes", "15 premium shirts", "Personal styling", "Accessories box"],
    drawDate: "Mon 27 Oct 2026 · 4:00 PM WAT",
    prizeCondition: "Bespoke, new",
    warranty: "Lifetime re-alterations",
    make: "Abuja Fashion Hub — Tailoring",
    model: "Gentleman's Signature Package",
    year: 2026,
    serialNo: "AFH-GS-2026-077",
    dimensions: "Fitted to client",
    color: "Client's choice from swatches",
    inclusions: ["Consultation & styling", "3 bespoke 2-piece suits", "1 tuxedo option", "Handmade leather shoes (2pr)", "15 Italian cotton shirts"],
    exclusions: ["Dry cleaning services", "Watches / jewelry"],
    maxTicketsPerUser: 150,
    marketValueKobo: mk(3_000_000),
  },
  {
    slug: "diamond-set-necklace",
    title: "18K Gold Diamond Set Necklace",
    category: "Jewelry",
    partner: "Lagos Jewels Co.",
    description:
      "A breathtaking 18K gold necklace set with 3.2 carats of VS-clarity natural diamonds. Comes with GIA certification and a complimentary jewelry appraisal for insurance.",
    prizeValueKobo: mk(6_500_000),
    entryPrice: mk(8_000),
    totalEntries: 5_000,
    entriesSold: 1_850,
    closes: "5 Nov · 23:59",
    daysUntilClose: 31,
    status: "LIVE",
    image: mercedesImage,
    imageAlt: "Stunning 18k gold diamond necklace on velvet display",
    accent: "lilac",
    specs: ["18K yellow gold", "3.2 ct total weight", "VS clarity diamonds", "GIA certified", "Appraisal included"],
    drawDate: "Thu 13 Nov 2026 · 5:00 PM WAT",
    prizeCondition: "Brand new, certified",
    warranty: "Lifetime cleaning & checking",
    make: "Lagos Jewels Co.",
    model: "Aurora Radiance Necklace",
    year: 2026,
    serialNo: "LJC-AR-32-774",
    dimensions: "45cm adjustable chain",
    color: "18K Yellow Gold",
    inclusions: ["Luxury presentation box", "GIA certificate", "Insurance appraisal", "First cleaning free", "Engraving service"],
    exclusions: ["Resizing over 2 sizes", "Damage from misuse"],
    maxTicketsPerUser: 25,
    marketValueKobo: mk(6_800_000),
  },
  {
    slug: "mens-luxury-watch",
    title: "Swiss Automatic Chronograph Watch",
    category: "Jewelry",
    partner: "Lagos Jewels Co.",
    description:
      "An iconic Swiss-made automatic chronograph in stainless steel with exhibition caseback. Paired with an authentic leather travel roll and 5-year service voucher.",
    prizeValueKobo: mk(3_800_000),
    entryPrice: mk(6_000),
    totalEntries: 6_500,
    entriesSold: 3_200,
    closes: "12 Oct · 23:59",
    daysUntilClose: 7,
    status: "CLOSING SOON",
    image: mercedesImage,
    imageAlt: "Luxury Swiss automatic chronograph watch close-up",
    accent: "sky",
    specs: ["Swiss automatic", "Chronograph function", "Sapphire crystal", "Exhibition caseback", "200m water resistance"],
    drawDate: "Fri 19 Sep 2026 · 4:00 PM WAT",
    prizeCondition: "Brand new with tags",
    warranty: "5-yr international warranty",
    make: "Swiss Master Chronometers",
    model: "SMC Navitimer Heritage 43",
    year: 2026,
    serialNo: "SMC-NH43-20871",
    dimensions: "43mm diameter · 14.5mm thick",
    color: "Stainless / Black dial",
    inclusions: ["Genuine alligator strap", "Steel bracelet included", "Watch winder box", "Travel roll", "5yr service voucher"],
    exclusions: ["Bracelet sizing beyond 2 links"],
    maxTicketsPerUser: 50,
    marketValueKobo: mk(4_000_000),
  },
  {
    slug: "small-business-grant",
    title: "₦10 Million Small Business Grant",
    category: "Business grants",
    partner: "Lekki Luxury Autos",
    description:
      "A ₦10 million naira grant package designed for ambitious Nigerian entrepreneurs. Includes funding, 3 months of business consulting, and a 1-year SME software subscription bundle.",
    prizeValueKobo: mk(10_000_000),
    entryPrice: mk(5_000),
    totalEntries: 15_000,
    entriesSold: 7_800,
    closes: "20 Nov · 23:59",
    daysUntilClose: 46,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Business handshake over modern workspace with Naira notes",
    accent: "mint",
    specs: ["₦10M grant funding", "3 months consulting", "SME software bundle", "Legal review", "Marketing support"],
    drawDate: "Tue 25 Nov 2026 · 5:00 PM WAT",
    prizeCondition: "Business grant — disbursed per plan",
    warranty: "N/A (consulting support 3 months)",
    make: "Rafilla SME Foundation",
    model: "Enterprise Boost Grant",
    year: 2026,
    serialNo: "RSEB-2026-042",
    dimensions: "N/A",
    color: "N/A",
    inclusions: ["₦10M grant", "Business plan review", "3 months McKinsey alum consulting", "₦500k SME SaaS credits", "Legal incorporation review"],
    exclusions: ["Disbursement conditional on business plan approval"],
    maxTicketsPerUser: 200,
    marketValueKobo: mk(10_000_000),
  },
  {
    slug: "tech-startup-seed",
    title: "Tech Founders Seed Package",
    category: "Business grants",
    partner: "Nova Electronics",
    description:
      "A comprehensive package for tech founders including ₦5M cash, AWS credits, mentorship, and free co-working space for 12 months at a premium Lagos hub.",
    prizeValueKobo: mk(7_500_000),
    entryPrice: mk(3_500),
    totalEntries: 18_000,
    entriesSold: 5_200,
    closes: "15 Dec · 23:59",
    daysUntilClose: 71,
    status: "UPCOMING",
    image: techBundleImage,
    imageAlt: "Tech founders working together in bright co-working space",
    accent: "coral",
    specs: ["₦5M cash", "AWS credits ($10k)", "12 mo co-working", "Mentorship (6 sessions)", "Legal template bundle"],
    drawDate: "Sat 20 Dec 2026 · 6:00 PM WAT",
    prizeCondition: "Grant package",
    warranty: "N/A",
    make: "Rafilla Tech Founders Program",
    model: "TFS Package Level 1",
    year: 2026,
    serialNo: "RTF-P1-182",
    dimensions: "N/A",
    color: "N/A",
    inclusions: ["₦5M cash disbursement", "$10,000 AWS credits", "12 months co-working (Lagos)", "6 x 1hr mentorship sessions"],
    exclusions: ["Co-working outside Lagos"],
    maxTicketsPerUser: 300,
    marketValueKobo: mk(7_500_000),
  },
  {
    slug: "dubai-vacation-package",
    title: "7-Day Dubai Luxury Vacation for 2",
    category: "Lifestyle",
    partner: "Abuja Fashion Hub",
    description:
      "A dream 7-day 5-star trip to Dubai for 2 including Business Class flights, Burj Al Arab stay, desert safari, yacht cruise, and spending money.",
    prizeValueKobo: mk(5_500_000),
    entryPrice: mk(5_500),
    totalEntries: 9_000,
    entriesSold: 4_100,
    closes: "25 Oct · 23:59",
    daysUntilClose: 20,
    status: "LIVE",
    image: mercedesImage,
    imageAlt: "Luxury Dubai skyline with palm island and luxury yacht",
    accent: "lemon",
    specs: ["7 nights Burj Al Arab", "Business class for 2", "Desert safari VIP", "Yacht cruise", "Spa day voucher"],
    drawDate: "Fri 31 Oct 2026 · 5:00 PM WAT",
    prizeCondition: "Pre-paid travel package",
    warranty: "Full travel insurance included",
    make: "Rafilla Travel & Lifestyle",
    model: "Dubai Signature Escape",
    year: 2026,
    serialNo: "RTRL-DSE-091",
    dimensions: "Valid 12 months",
    color: "N/A",
    inclusions: ["Business class flights (2pax)", "7 nights Burj Al Arab suite", "Daily breakfast", "Desert safari + dinner", "Private yacht half-day", "$2,000 spending"],
    exclusions: ["Travel dates subject to availability", "Visa costs if applicable"],
    maxTicketsPerUser: 75,
    marketValueKobo: mk(5_800_000),
  },
  {
    slug: "home-renovation-voucher",
    title: "Full Home Renovation Package",
    category: "Lifestyle",
    partner: "Abeokuta Homes",
    description:
      "A complete interior design and renovation package covering a 3-bedroom apartment — kitchen, bathrooms, flooring, painting, and premium furniture.",
    prizeValueKobo: mk(8_000_000),
    entryPrice: mk(4_000),
    totalEntries: 14_000,
    entriesSold: 6_300,
    closes: "30 Oct · 23:59",
    daysUntilClose: 25,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Beautifully renovated luxury home interior",
    accent: "mint",
    specs: ["3-bed full reno", "Interior design service", "Premium kitchen cabinetry", "All rooms flooring", "Custom lighting"],
    drawDate: "Thu 6 Nov 2026 · 5:00 PM WAT",
    prizeCondition: "Service package",
    warranty: "1-yr workmanship warranty",
    make: "Abeokuta Homes — Interiors",
    model: "Signature 3-Bed Renovation",
    year: 2026,
    serialNo: "AH-SR-307",
    dimensions: "Up to 220 sqm covered",
    color: "Client's choice",
    inclusions: ["Full design consultation", "3D renders", "Kitchen fully fitted", "All bathrooms redone", "Vitallium tiles all floors", "POP & painting"],
    exclusions: ["Structural changes", "Appliances outside kitchen set"],
    maxTicketsPerUser: 200,
    marketValueKobo: mk(8_500_000),
  },
  {
    slug: "vintage-watches-collection",
    title: "Vintage Collector's 5-Watch Set",
    category: "Collectibles",
    partner: "Lagos Jewels Co.",
    description:
      "A curated set of 5 authenticated vintage watches from the 1960s-1980s: Rolex, Omega, Longines, Seiko, and a rare Nigerian-made Grand. All serviced and with full provenance documentation.",
    prizeValueKobo: mk(9_000_000),
    entryPrice: mk(10_000),
    totalEntries: 4_500,
    entriesSold: 1_100,
    closes: "1 Dec · 23:59",
    daysUntilClose: 57,
    status: "LIVE",
    image: mercedesImage,
    imageAlt: "Collection of 5 vintage luxury watches in wooden display case",
    accent: "lilac",
    specs: ["5 authenticated vintages", "Rolex Oysterdate 1972", "Omega Speedmaster 1984", "Longines Flagship 1968", "Seiko Grand 1978", "Rare Nigeria-made Grand"],
    drawDate: "Thu 4 Dec 2026 · 6:00 PM WAT",
    prizeCondition: "Vintage — excellent restored condition",
    warranty: "Authenticity guarantee, 30-day return",
    make: "Various — authenticated by Lagos Jewels Co.",
    model: "Heritage Collection HC-5",
    year: "1960s-1980s",
    serialNo: "LJC-HC5-014",
    dimensions: "Mahogany box 40x30x15cm",
    color: "Various dials",
    inclusions: ["5 watches", "Bespoke mahogany box", "Certificate for each", "Service records", "Digital appraisal"],
    exclusions: ["Subsequent servicing costs"],
    maxTicketsPerUser: 30,
    marketValueKobo: mk(9_500_000),
  },
  {
    slug: "first-edition-novel-collection",
    title: "Nigerian Literary First Editions Set",
    category: "Collectibles",
    partner: "Abuja Fashion Hub",
    description:
      "A rare collection of 15 signed first-edition Nigerian literary classics including Achebe, Soyinka, Okri, Adichie, and more. Custom leather slipcase with certificate of authenticity.",
    prizeValueKobo: mk(2_200_000),
    entryPrice: mk(2_200),
    totalEntries: 10_000,
    entriesSold: 3_700,
    closes: "5 Dec · 23:59",
    daysUntilClose: 61,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Signed Nigerian literary classics displayed on custom bookshelf",
    accent: "sky",
    specs: ["15 first editions", "Mostly signed", "Custom leather slipcase", "Achebe, Soyinka, Okri, Adichie", "Full provenance"],
    drawDate: "Tue 9 Dec 2026 · 4:00 PM WAT",
    prizeCondition: "Very fine / fine condition",
    warranty: "Lifetime authenticity guarantee",
    make: "Curated by Rafilla Literary Foundation",
    model: "Nigeria Classics Series NCS-1",
    year: "1958-2020s",
    serialNo: "RLF-NCS1-007",
    dimensions: "Custom leather case 60x50x40cm",
    color: "Genuine morocco leather",
    inclusions: ["15 volumes", "4 signed by author", "Leather slipcase custom", "Digital provenance ledger", "Letter of curation"],
    exclusions: ["Damage from neglect / fire / water"],
    maxTicketsPerUser: 100,
    marketValueKobo: mk(2_400_000),
  },
  {
    slug: "toyota-camry-xse-2025",
    title: "Toyota Camry XSE 2025",
    category: "Vehicles",
    partner: "Lekki Luxury Autos",
    description:
      "The stylish and dependable Toyota Camry XSE with sport-tuned suspension, premium cockpit, and advanced driver assist. Perfect daily driver with legendary reliability.",
    prizeValueKobo: mk(16_500_000),
    entryPrice: mk(7_500),
    totalEntries: 9_500,
    entriesSold: 5_900,
    closes: "8 Oct · 23:59",
    daysUntilClose: 3,
    status: "CLOSING SOON",
    image: mercedesImage,
    imageAlt: "Blue metallic Toyota Camry XSE sport sedan",
    accent: "sky",
    specs: ["2025 model", "XSE sport trim", "2.5L Hybrid AWD", "Sport suspension", "9-speaker JBL audio"],
    drawDate: "Tue 7 Oct 2026 · 5:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "3-yr warranty + free servicing",
    make: "Toyota",
    model: "Camry XSE Hybrid",
    year: 2025,
    serialNo: "TY-CAMXSE-25-8821",
    dimensions: "4885 x 1840 x 1445 mm",
    color: "Reservoir Blue Metallic",
    inclusions: ["Full tank fuel", "1yr comprehensive insurance", "Floor mats premium", "Paint sealant", "3 free services"],
    exclusions: ["Drivers license / registration renewal"],
    maxTicketsPerUser: 80,
    marketValueKobo: mk(17_000_000),
  },
  {
    slug: "honda-pilot-elite-2025",
    title: "Honda Pilot Elite 2025 (8-seater)",
    category: "Vehicles",
    partner: "Lekki Luxury Autos",
    description:
      "A spacious family SUV with 8 seats, premium interior, captain chairs, AWD capability, and the legendary Honda build quality everyone trusts.",
    prizeValueKobo: mk(28_000_000),
    entryPrice: mk(12_000),
    totalEntries: 7_000,
    entriesSold: 2_900,
    closes: "22 Nov · 23:59",
    daysUntilClose: 48,
    status: "LIVE",
    image: mercedesImage,
    imageAlt: "White Honda Pilot Elite SUV with family inside",
    accent: "lemon",
    specs: ["8-seater capacity", "AWD", "TrailSport rugged trim", "Honda Sensing safety suite", "Panoramic roof"],
    drawDate: "Mon 24 Nov 2026 · 6:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "3-yr / 100k km warranty",
    make: "Honda",
    model: "Pilot Elite",
    year: 2025,
    serialNo: "HD-PLT-25-20118",
    dimensions: "5080 x 1996 x 1805 mm",
    color: "Platinum White Pearl",
    inclusions: ["Roof rails", "Tow package", "All-weather mats", "2yr insurance", "4 free services"],
    exclusions: ["Personal number plates cost"],
    maxTicketsPerUser: 60,
    marketValueKobo: mk(29_500_000),
  },
  {
    slug: "sony-alpha-a7rv-camera",
    title: "Sony Alpha A7R V Pro Filmmaker Kit",
    category: "Electronics",
    partner: "Nova Electronics",
    description:
      "A complete pro filmmaker package: Sony A7R V 61MP body with 3 premium lenses, DJI RS3 Pro gimbal, 2TB storage, Atomos monitor, and all accessories.",
    prizeValueKobo: mk(3_200_000),
    entryPrice: mk(6_500),
    totalEntries: 8_500,
    entriesSold: 4_400,
    closes: "14 Oct · 23:59",
    daysUntilClose: 9,
    status: "LIVE",
    image: techBundleImage,
    imageAlt: "Sony A7R V camera with lenses, gimbal, and accessories laid out",
    accent: "coral",
    specs: ["A7R V 61MP body", "3 premium lenses", "DJI RS3 Pro gimbal", "Atomos Ninja V", "640GB CFexpress"],
    drawDate: "Mon 20 Oct 2026 · 5:00 PM WAT",
    prizeCondition: "Brand new (body) — open box mint",
    warranty: "2-yr Sony Nigeria warranty",
    make: "Sony / DJI / Atomos",
    model: "Sony A7R V Pro Filmmaker Bundle",
    year: 2026,
    serialNo: "SA7R-Pro-66-301",
    dimensions: "Body 129 x 96 x 80 mm (approx)",
    color: "Black",
    inclusions: ["Sony A7R V body", "24-70mm GM II f/2.8", "85mm f/1.4 GM", "16-35mm f/4 PZ", "DJI RS3 Pro gimbal", "Atomos Ninja V", "2x CFexpress (640GB + 320GB)"],
    exclusions: ["Computers / editing software"],
    maxTicketsPerUser: 60,
    marketValueKobo: mk(3_450_000),
  },
  {
    slug: "4k-home-theatre-package",
    title: "4K Dolby Atmos Home Theatre Package",
    category: "Electronics",
    partner: "Nova Electronics",
    description:
      "Transform your living room into a cinema: 75\" OLED TV, 5.1.2 Dolby Atmos speaker system, 4K projector backup, premium recliner seating, and acoustic treatment.",
    prizeValueKobo: mk(4_800_000),
    entryPrice: mk(8_000),
    totalEntries: 10_500,
    entriesSold: 3_800,
    closes: "28 Nov · 23:59",
    daysUntilClose: 54,
    status: "LIVE",
    image: techBundleImage,
    imageAlt: "Luxury home theater room with big screen, recliners, atmos speakers",
    accent: "lilac",
    specs: ["75\" OLED EVO TV", "5.1.2 Atmos speakers", "120\" motorized screen", "4K laser projector", "2 leather recliners"],
    drawDate: "Fri 5 Dec 2026 · 6:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "2-yr manufacturer + installer",
    make: "LG / Epson / Klipsch",
    model: "Cinematic Studio Home CSH-2",
    year: 2026,
    serialNo: "NOVA-CSH2-088",
    dimensions: "TV 75 inch + 120 inch screen",
    color: "Matte Black / Brown recliners",
    inclusions: ["75\" LG C4 OLED", "Klipsch 5.1.2 system", "Epson LS800 UST", "120\" ALR motorized", "2 recliners with heat+massage", "Full install + tuning"],
    exclusions: ["Room construction / refurbishment"],
    maxTicketsPerUser: 80,
    marketValueKobo: mk(5_200_000),
  },
  {
    slug: "1-bedroom-terrace-abuja",
    title: "1-Bed Terrace Duplex — Wuye, Abuja",
    category: "Homes",
    partner: "Abeokuta Homes",
    description:
      "Modern 1-bed terrace duplex in the fast-developing Wuye district of Abuja. Features spacious rooms, dedicated parking, and is within walking distance to shops.",
    prizeValueKobo: mk(25_000_000),
    entryPrice: mk(3_000),
    totalEntries: 20_000,
    entriesSold: 8_900,
    closes: "12 Jan · 23:59",
    daysUntilClose: 98,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Modern 1-bedroom terrace exterior with private entrance",
    accent: "sky",
    specs: ["1 large bedroom ensuite", "Kitchen fitted", "Dining area", "Private parking", "Tiled compound"],
    drawDate: "Sat 17 Jan 2026 · 5:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "1-yr workmanship",
    make: "Abeokuta Homes Ltd",
    model: "Abuja Urban Terraces A3",
    year: 2026,
    serialNo: "AH-AUT-A3-017",
    dimensions: "120 sqm built",
    color: "Off-white / charcoal doors",
    inclusions: ["AC in bedroom & living", "Water heater", "Wardrobe fitted", "Kitchen cabinets + island", "Fenced compound"],
    exclusions: ["Land documentation / C-of-O"],
    maxTicketsPerUser: 400,
    marketValueKobo: mk(26_500_000),
  },
  {
    slug: "gucci-x-lv-bundle",
    title: "Luxury Handbag & Accessory Bundle",
    category: "Fashion",
    partner: "Abuja Fashion Hub",
    description:
      "A curated collection of 4 iconic designer pieces: Gucci Marmont bag, Louis Vuitton Speedy, Louboutin heels, and a silk scarf set with storage.",
    prizeValueKobo: mk(2_400_000),
    entryPrice: mk(4_000),
    totalEntries: 7_500,
    entriesSold: 5_100,
    closes: "3 Oct · 23:59",
    daysUntilClose: 0,
    status: "CLOSING SOON",
    image: mercedesImage,
    imageAlt: "Designer Gucci and Louis Vuitton handbags with accessories",
    accent: "coral",
    specs: ["Gucci Marmont MM", "LV Speedy Bandoulière 30", "Louboutin Pigalle 100mm", "Silk scarf set", "Storage dust bags"],
    drawDate: "Sun 5 Oct 2026 · 4:00 PM WAT",
    prizeCondition: "Brand new, with original packaging",
    warranty: "Authenticity lifetime guarantee",
    make: "Gucci / Louis Vuitton / Christian Louboutin",
    model: "Iconic 4-Piece Collection",
    year: 2026,
    serialNo: "AFH-ICON4-058",
    dimensions: "Box set 60x50x30cm",
    color: "GG Marmont Black / LV Monogram / Nude heels",
    inclusions: ["All 4 pieces", "Original dust bags & boxes", "Certificate of authenticity", "Storage box"],
    exclusions: ["Re-soling of heels"],
    maxTicketsPerUser: 60,
    marketValueKobo: mk(2_600_000),
  },
  {
    slug: "gold-bangle-collection",
    title: "22K Gold Bangle Set (6 pieces)",
    category: "Jewelry",
    partner: "Lagos Jewels Co.",
    description:
      "A stunning traditional set of 6 hollow-work 22K gold bangles with intricate filigree work. 120 grams total weight with assay certification.",
    prizeValueKobo: mk(4_200_000),
    entryPrice: mk(5_500),
    totalEntries: 7_000,
    entriesSold: 2_600,
    closes: "18 Nov · 23:59",
    daysUntilClose: 44,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Traditional 22k gold bangles arranged on silk cushion",
    accent: "lemon",
    specs: ["22K solid gold", "6 bangles set", "~120 grams total", "Assay certified", "Intricate filigree"],
    drawDate: "Wed 26 Nov 2026 · 5:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "Lifetime buyback at 90% of gold spot",
    make: "Lagos Jewels Co. — Atelier",
    model: "Ade Ori-Okuta Set",
    year: 2026,
    serialNo: "LJC-AOO-120-33",
    dimensions: "Bangle internal diameter 6.2cm (standard)",
    color: "22K Yellow Gold",
    inclusions: ["6 bangles set", "Wooden presentation box", "Assay office certificate", "Digital appraisal"],
    exclusions: ["Gemstone additions — not included here"],
    maxTicketsPerUser: 40,
    marketValueKobo: mk(4_350_000),
  },
  {
    slug: "nse-portfolio-grant",
    title: "₦5M NSE Stock Portfolio + Mentorship",
    category: "Business grants",
    partner: "Lagos Jewels Co.",
    description:
      "A ₦5 million Nigerian Stock Exchange portfolio invested in top-tier bluechip stocks, with 6 months of professional portfolio management and monthly reports.",
    prizeValueKobo: mk(5_000_000),
    entryPrice: mk(5_000),
    totalEntries: 11_000,
    entriesSold: 4_800,
    closes: "10 Jan · 23:59",
    daysUntilClose: 96,
    status: "UPCOMING",
    image: techBundleImage,
    imageAlt: "Stock trading chart display on NSE with Nigerian currency",
    accent: "mint",
    specs: ["₦5M bluechip portfolio", "6 mo managed", "Monthly reports", "1-on-1 investing workshop", "CSCS account opened"],
    drawDate: "Fri 16 Jan 2026 · 5:00 PM WAT",
    prizeCondition: "Managed investment portfolio",
    warranty: "6 month management fee waived",
    make: "Rafilla Capital Markets Program",
    model: "Bluechip Starter Portfolio",
    year: 2026,
    serialNo: "RCMS-BSP-042",
    dimensions: "N/A",
    color: "N/A",
    inclusions: ["CSCS account opening", "₦5M invested", "6 months professional Mgmt", "Monthly reports", "2hr investing workshop"],
    exclusions: ["Taxes on gains — winner responsibility"],
    maxTicketsPerUser: 200,
    marketValueKobo: mk(5_000_000),
  },
  {
    slug: "santorini-greek-island-holiday",
    title: "10-Day Greek Islands Sailing (Santorini + Mykonos)",
    category: "Lifestyle",
    partner: "Lagos Jewels Co.",
    description:
      "10 days in the Cyclades aboard a private sailing catamaran for 4 friends, stopping at Santorini, Mykonos, Paros, Ios, with a private chef on board.",
    prizeValueKobo: mk(8_500_000),
    entryPrice: mk(10_000),
    totalEntries: 12_000,
    entriesSold: 6_100,
    closes: "5 Feb · 23:59",
    daysUntilClose: 122,
    status: "UPCOMING",
    image: apartmentImage,
    imageAlt: "Luxury catamaran sailing the Greek islands with Santorini caldera view",
    accent: "sky",
    specs: ["Private catamaran (5 cabins)", "10 days 9 nights", "Santorini, Mykonos, Paros, Ios", "Private skipper + chef", "Watersports gear"],
    drawDate: "Wed 11 Feb 2026 · 6:00 PM WAT",
    prizeCondition: "Charter package",
    warranty: "Crewed charter insurance included",
    make: "Rafilla Travel & Lifestyle",
    model: "Aegean Dream Charter",
    year: 2026,
    serialNo: "RTRL-AEG-101",
    dimensions: "Catamaran Lagoon 52 (5 cabins)",
    color: "N/A",
    inclusions: ["Charter fees 10 days", "Skipper + hostess + chef", "All meals on board", "Fuel", "Port fees", "Stand up paddle + snorkel"],
    exclusions: ["Flights to Athens", "Personal spending / tips"],
    maxTicketsPerUser: 120,
    marketValueKobo: mk(9_200_000),
  },
  {
    slug: "wellness-spa-retreat",
    title: "7-Day Wellness & Spa Retreat (Lagos + Obudu)",
    category: "Lifestyle",
    partner: "Abuja Fashion Hub",
    description:
      "A total mind and body reset: 3 days at Lagos premier wellness spa + 4 days at the stunning Obudu Cattle Ranch Mountain Resort with helicopter transfer included.",
    prizeValueKobo: mk(2_100_000),
    entryPrice: mk(2_500),
    totalEntries: 11_500,
    entriesSold: 6_900,
    closes: "1 Nov · 23:59",
    daysUntilClose: 27,
    status: "LIVE",
    image: apartmentImage,
    imageAlt: "Wellness spa treatment room and Obudu mountain scenic view",
    accent: "mint",
    specs: ["3 days Lagos spa", "4 days Obudu resort", "Helicopter transfer scenic", "Daily treatments", "Nutrition & yoga"],
    drawDate: "Tue 4 Nov 2026 · 4:00 PM WAT",
    prizeCondition: "Pre-paid retreat",
    warranty: "Rescheduling up to 1 time",
    make: "Rafilla Wellness Series",
    model: "Complete R&R Retreat",
    year: 2026,
    serialNo: "RWS-CRR-112",
    dimensions: "N/A",
    color: "N/A",
    inclusions: ["Spa stay Lagos 3 nights all-inclusive", "Obudu 4 nights suite", "Scenic helicopter transfer", "Daily spa treatments", "Private yoga", "Meal plans nutritionist"],
    exclusions: ["Extra guests beyond 1"],
    maxTicketsPerUser: 150,
    marketValueKobo: mk(2_250_000),
  },
  {
    slug: "rare-art-collection",
    title: "Nigerian Masters Art Collection (7 works)",
    category: "Collectibles",
    partner: "Lekki Luxury Autos",
    description:
      "An exclusive collection of 7 original artworks from renowned Nigerian masters including Ben Enwonwu, Bruce Onobrakpeya, and contemporary Nigerian artists — with gallery certificate.",
    prizeValueKobo: mk(11_000_000),
    entryPrice: mk(12_000),
    totalEntries: 5_000,
    entriesSold: 1_700,
    closes: "15 Jan · 23:59",
    daysUntilClose: 101,
    status: "UPCOMING",
    image: apartmentImage,
    imageAlt: "Gallery room with contemporary Nigerian artworks on wall",
    accent: "coral",
    specs: ["7 original works", "Enwonwu / Onobrakpeya included", "Contemporary masters", "Gallery provenance", "Museum framing"],
    drawDate: "Thu 22 Jan 2026 · 6:00 PM WAT",
    prizeCondition: "Original works, excellent condition",
    warranty: "Certificate of authenticity",
    make: "Various — curated by Terra Kulture",
    model: "Nigeria Masters 7-Piece Set",
    year: "1970s - 2020s",
    serialNo: "TK-NMS7-018",
    dimensions: "Various largest 1.2m x 0.9m",
    color: "Museum glass / timber frames",
    inclusions: ["7 artworks", "Certificate of provenance", "Professional installation", "Digital archive ledger", "1 free professional cleaning"],
    exclusions: ["Insurance policy (but appraisal provided)"],
    maxTicketsPerUser: 20,
    marketValueKobo: mk(11_800_000),
  },
  {
    slug: "vintage-vinyl-collection",
    title: "500 Premium Vintage Vinyl Records Collection",
    category: "Collectibles",
    partner: "Nova Electronics",
    description:
      "A handpicked collector's crate of 500 premium vinyl records spanning Highlife, Afrobeat, Juju, Funk, Soul, Jazz, Rock, Disco, and modern classics. Includes a free turntable.",
    prizeValueKobo: mk(1_600_000),
    entryPrice: mk(2_000),
    totalEntries: 9_500,
    entriesSold: 4_200,
    closes: "20 Oct · 23:59",
    daysUntilClose: 15,
    status: "LIVE",
    image: techBundleImage,
    imageAlt: "Vintage vinyl records crate with turntable setup and album covers",
    accent: "lilac",
    specs: ["500 vinyl records", "Afrobeat, Highlife, Soul, Jazz, Funk", "Turntable (Audio-Technica)", "Discwasher care kit", "Custom wooden crate"],
    drawDate: "Tue 28 Oct 2026 · 4:00 PM WAT",
    prizeCondition: "VG+ to NM average condition",
    warranty: "Grade accuracy guaranteed",
    make: "Curated by Rafilla Records Archive",
    model: "Collector's 500 Set",
    year: "1960s - 2020s",
    serialNo: "RRA-500-033",
    dimensions: "Crate 90x70x60cm approx",
    color: "Walnut crate",
    inclusions: ["500 records (graded)", "Custom walnut crate", "Audio-Technica AT-LP120X turntable", "Discwasher cleaning system", "Record catalog digital"],
    exclusions: ["Speakers / amplifier"],
    maxTicketsPerUser: 200,
    marketValueKobo: mk(1_750_000),
  },
  {
    slug: "tesla-model-y-long-range",
    title: "Tesla Model Y Long Range AWD",
    category: "Vehicles",
    partner: "Lekki Luxury Autos",
    description:
      "The future is now — Tesla's best-selling electric SUV with Long Range AWD, 533km range, Autopilot, Premium interior, and a home charging station included.",
    prizeValueKobo: mk(33_000_000),
    entryPrice: mk(11_000),
    totalEntries: 10_000,
    entriesSold: 3_600,
    closes: "8 Jan · 23:59",
    daysUntilClose: 94,
    status: "UPCOMING",
    image: mercedesImage,
    imageAlt: "White Tesla Model Y electric SUV with panoramic glass roof",
    accent: "mint",
    specs: ["Long Range AWD", "533km WLTP range", "Autopilot included", "Ultra white premium interior", "22\" Überturbine wheels"],
    drawDate: "Thu 15 Jan 2026 · 6:00 PM WAT",
    prizeCondition: "Brand new, direct import",
    warranty: "Tesla 4-yr / 80k km + battery 8-yr",
    make: "Tesla",
    model: "Model Y Long Range AWD",
    year: 2026,
    serialNo: "TS-MYLR-26-77120",
    dimensions: "4751 x 1921 x 1624 mm",
    color: "Pearl White Multi-Coat",
    inclusions: ["Wall Connector home charger", "All weather floor liner kit", "Tinted windows ceramic", "1yr registration + insurance"],
    exclusions: ["Personalization of delivery date"],
    maxTicketsPerUser: 80,
    marketValueKobo: mk(34_500_000),
  },
  {
    slug: "ikeja-shopping-spree",
    title: "₦1,000,000 Ikeja City Mall Shopping Spree",
    category: "Lifestyle",
    partner: "Abeokuta Homes",
    description:
      "A fun-filled shopping experience at Ikeja City Mall with ₦1M loaded on a gift card, plus a personal stylist and lunch at a premium restaurant for you and 3 friends.",
    prizeValueKobo: mk(1_150_000),
    entryPrice: mk(1_500),
    totalEntries: 16_000,
    entriesSold: 11_200,
    closes: "6 Oct · 23:59",
    daysUntilClose: 1,
    status: "CLOSING SOON",
    image: apartmentImage,
    imageAlt: "Modern shopping mall interior with Nigerian shoppers",
    accent: "lemon",
    specs: ["₦1M gift card ICM", "Personal stylist", "Lunch premium restaurant (4 pax)", "Chauffeur for the day", "Photographer"],
    drawDate: "Thu 9 Oct 2026 · 4:00 PM WAT",
    prizeCondition: "Experience + gift package",
    warranty: "Redeemable for 6 months",
    make: "Rafilla Lifestyle Experiences",
    model: "ICM Mega Spree 2026",
    year: 2026,
    serialNo: "RLS-ICM-055",
    dimensions: "N/A",
    color: "N/A",
    inclusions: ["₦1M gift card", "Stylist 8 hours", "Restaurant vouchers (₦150k)", "Chauffeur Lexus (8hrs)", "Photographer content"],
    exclusions: ["Shopee / items outside ICM"],
    maxTicketsPerUser: 300,
    marketValueKobo: mk(1_150_000),
  },
  {
    slug: "mini-cooper-s-2025",
    title: "MINI Cooper S 3-Door 2025",
    category: "Vehicles",
    partner: "Lekki Luxury Autos",
    description:
      "Iconic fun — the all-electric MINI Cooper S in British Racing Green with premium JCW trim package. Perfect city car with personality.",
    prizeValueKobo: mk(18_500_000),
    entryPrice: mk(9_000),
    totalEntries: 8_800,
    entriesSold: 3_100,
    closes: "25 Jan · 23:59",
    daysUntilClose: 111,
    status: "UPCOMING",
    image: mercedesImage,
    imageAlt: "British Racing Green MINI Cooper 3-door sport hatchback",
    accent: "coral",
    specs: ["Electric SE 3-door", "JCW Sport trim", "250km range", "Premium leather lounge", "Harman Kardon audio"],
    drawDate: "Mon 2 Feb 2026 · 5:00 PM WAT",
    prizeCondition: "Brand new",
    warranty: "3-yr / 100k km warranty",
    make: "MINI (BMW Group)",
    model: "MINI Cooper SE 3-Door JCW Trim",
    year: 2025,
    serialNo: "MN-CSE-JCW-25-5512",
    dimensions: "3858 x 1727 x 1414 mm",
    color: "British Racing Green IV",
    inclusions: ["Level 2 home charger", "MINI roof rails black", "Union Jack mirror caps", "1yr comprehensive insurance", "Delivery"],
    exclusions: ["Custom wrapping"],
    maxTicketsPerUser: 70,
    marketValueKobo: mk(19_500_000),
  },
];

export const featuredCompetition =
  competitions.find((competition) => competition.featured) ?? competitions[0];

export const featuredCompetitions: Competition[] = (() => {
  const explicitlyFeatured = competitions.filter((c) => c.featured);
  if (explicitlyFeatured.length >= 8) return explicitlyFeatured.slice(0, 8);
  const remaining = competitions
    .filter((c) => !c.featured && c.status !== "COMPLETED")
    .sort((a, b) => b.entriesSold / b.totalEntries - a.entriesSold / a.totalEntries);
  const slotsLeft = 8 - explicitlyFeatured.length;
  return [...explicitlyFeatured, ...remaining.slice(0, slotsLeft)];
})();

export const formatNaira = (amountKobo: number) =>
  new Intl.NumberFormat("en-NG", {
    style: "currency",
    currency: "NGN",
    maximumFractionDigits: 0,
  }).format(Math.round(amountKobo / 100));

export const getProgress = (competition: Competition) =>
  Math.min(100, Math.round((competition.entriesSold / competition.totalEntries) * 100));

export const getCompetition = (slug: string) =>
  competitions.find((competition) => competition.slug === slug);

export type SortKey =
  | "ending-soon"
  | "newest"
  | "price-asc"
  | "price-desc"
  | "most-entries"
  | "featured-first";

export function applySort(list: Competition[], sort: SortKey): Competition[] {
  const copy = [...list];
  switch (sort) {
    case "ending-soon":
      return copy.sort((a, b) => a.daysUntilClose - b.daysUntilClose);
    case "newest":
      return copy.reverse();
    case "price-asc":
      return copy.sort((a, b) => a.entryPrice - b.entryPrice);
    case "price-desc":
      return copy.sort((a, b) => b.entryPrice - a.entryPrice);
    case "most-entries":
      return copy.sort((a, b) => b.entriesSold - a.entriesSold);
    case "featured-first":
      return copy.sort((a, b) => Number(!!b.featured) - Number(!!a.featured));
    default:
      return copy;
  }
}

export const faqs = [
  {
    q: "What is Rafilla?",
    a: "Rafilla is a platform for premium prize competitions. You choose a competition, purchase entries, and follow the journey to the draw.",
  },
  {
    q: "How do I enter a competition?",
    a: "Create an account, fund your Rafilla Wallet when wallet funding is available, choose a competition, and purchase entries.",
  },
  {
    q: "How are winners selected?",
    a: "After a competition closes, eligible entries are frozen and the draw is conducted through a secure, verifiable process.",
  },
  {
    q: "Can I withdraw my Rafilla Wallet balance?",
    a: "The standard Rafilla Wallet is spend-only. It is designed for funding competition entries, not cash withdrawals.",
  },
  {
    q: "What are referral earnings?",
    a: "Referral earnings are separate from the spend-only wallet. Eligible earnings may be used for entries or requested as a cash payout, subject to the applicable review process.",
  },
  {
    q: "Is my account secure?",
    a: "Rafilla uses standard authentication and account security practices, with email and phone verification during onboarding.",
  },
  {
    q: "What happens if a competition is cancelled?",
    a: "If a competition does not proceed, entry amounts are refunded back to the Rafilla Wallet in line with the competition rules.",
  },
];

export type WinnerCard = {
  id: string;
  winnerName: string;
  prize: string;
  competition: string;
  drawDate: string;
  location: string;
  amount: string;
  verified: boolean;
  image: string;
  imageAlt: string;
};

export const competitionFaqs = [
  {
    q: "How many tickets can I buy for one competition?",
    a: "Each competition has a per-user maximum ticket limit displayed in the Ticket Info tab. This keeps the draws fair and prevents single parties from dominating.",
  },
  {
    q: "When exactly does the draw happen and can I watch it live?",
    a: "Draws take place on the date and time published for the competition. We provide a live stream link for all draws and publish the verification record on the Draw Verification page.",
  },
  {
    q: "What happens if I win? How will I be contacted?",
    a: "Winners are contacted via the email and phone on their account within 48 hours of the verified draw. We publish first name + last initial publicly until the full winner consent is received.",
  },
  {
    q: "How long do I have to claim my prize?",
    a: "The claim window is 14 calendar days from the draw date. If a winner does not respond or complete verification, we perform a redraw per the Competition Rules.",
  },
  {
    q: "Can I buy tickets for someone else as a gift?",
    a: "Tickets are tied to the Rafilla account that purchased them. To gift, the recipient must have their own verified Rafilla account and you can transfer wallet funds to them to enter.",
  },
  {
    q: "Are there any hidden fees on top of the ticket price?",
    a: "No. The displayed ticket price is inclusive of all platform fees. Winners are not required to pay anything to receive a prize (tax registration, where applicable, is separate).",
  },
  {
    q: "How do you make sure the draw is fair and not rigged?",
    a: "All eligible entries are frozen at close. A cryptographically secure process (HMAC_DRBG) with a published seed produces the result, and the full record is posted to our public Draw Verification page.",
  },
  {
    q: "If the competition doesn't sell enough tickets, will it still take place?",
    a: "Rafilla runs every published draw regardless of tickets sold. If for any rare reason a draw is cancelled, ticket prices are refunded in full to the Rafilla wallet.",
  },
];

export const winnerCards: WinnerCard[] = [
  {
    id: "winner-1",
    winnerName: "Adebayo O.",
    prize: "Mercedes-Benz C-Class 2025",
    competition: "Executive Sedan Draw",
    drawDate: "28 Feb 2026",
    location: "Lagos, Nigeria",
    amount: "₦12,000,000",
    verified: true,
    image: mercedesImage,
    imageAlt: "Silver Mercedes-Benz C-Class sedan",
  },
  {
    id: "winner-2",
    winnerName: "Chiamaka N.",
    prize: "Nova X1 Bundle",
    competition: "Tech Bundle Launch",
    drawDate: "14 Feb 2026",
    location: "Abuja, Nigeria",
    amount: "₦1,950,000",
    verified: true,
    image: techBundleImage,
    imageAlt: "Flagship smartphone and connected tech bundle",
  },
  {
    id: "winner-3",
    winnerName: "Ifeanyi K.",
    prize: "Luxury 2-Bed Apartment",
    competition: "City Living Raffle",
    drawDate: "02 Feb 2026",
    location: "Port Harcourt, Nigeria",
    amount: "₦38,000,000",
    verified: true,
    image: apartmentImage,
    imageAlt: "Bright contemporary apartment lounge",
  },
];
