/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeAPartnerRouteImport } from './routes/become-a-partner'
import { Route as CompetitionRulesRouteImport } from './routes/competition-rules'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsRouteImport } from './routes/robots'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCompetitionsRouteImport } from './routes/admin.competitions'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CompetitionsIndexRouteImport } from './routes/competitions/index'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCompetitionsRouteImport } from './routes/dashboard.competitions'
import { Route as DashboardEntriesRouteImport } from './routes/dashboard.entries'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardRewardPoolRouteImport } from './routes/dashboard.reward-pool'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DrawVerificationCampaignRouteImport } from './routes/draw-verification.$campaign'
import { Route as DrawVerificationSlugRouteImport } from './routes/draw-verification.$slug'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerAnalyticsRouteImport } from './routes/partner.analytics'
import { Route as PartnerListingsRouteImport } from './routes/partner.listings'
import { Route as PartnerProfileRouteImport } from './routes/partner.profile'
import { Route as PartnerSettlementsRouteImport } from './routes/partner.settlements'
import { Route as PartnerSubmitRouteImport } from './routes/partner.submit'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as DashboardReferralsPayoutRouteImport } from './routes/dashboard.referrals.payout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAPartnerRoute = BecomeAPartnerRouteImport.update({
  id: '/become-a-partner',
  path: '/become-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRulesRoute = CompetitionRulesRouteImport.update({
  id: '/competition-rules',
  path: '/competition-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsRoute = RobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCompetitionsRoute = AdminCompetitionsRouteImport.update({
  id: '/admin/competitions',
  path: '/admin/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/admin/config',
  path: '/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/admin/fraud',
  path: '/admin/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsIndexRoute = CompetitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompetitionsRoute,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompetitionsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompetitionsRoute = DashboardCompetitionsRouteImport.update({
  id: '/dashboard/competitions',
  path: '/dashboard/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEntriesRoute = DashboardEntriesRouteImport.update({
  id: '/dashboard/entries',
  path: '/dashboard/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/dashboard/referrals',
  path: '/dashboard/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRewardPoolRoute = DashboardRewardPoolRouteImport.update({
  id: '/dashboard/reward-pool',
  path: '/dashboard/reward-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/dashboard/security',
  path: '/dashboard/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/dashboard/transactions',
  path: '/dashboard/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/dashboard/wallet',
  path: '/dashboard/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawVerificationCampaignRoute =
  DrawVerificationCampaignRouteImport.update({
    id: '/draw-verification/$campaign',
    path: '/draw-verification/$campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const DrawVerificationSlugRoute = DrawVerificationSlugRouteImport.update({
  id: '/draw-verification/$slug',
  path: '/draw-verification/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAnalyticsRoute = PartnerAnalyticsRouteImport.update({
  id: '/partner/analytics',
  path: '/partner/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerListingsRoute = PartnerListingsRouteImport.update({
  id: '/partner/listings',
  path: '/partner/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProfileRoute = PartnerProfileRouteImport.update({
  id: '/partner/profile',
  path: '/partner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSettlementsRoute = PartnerSettlementsRouteImport.update({
  id: '/partner/settlements',
  path: '/partner/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSubmitRoute = PartnerSubmitRouteImport.update({
  id: '/partner/submit',
  path: '/partner/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReferralsPayoutRoute =
  DashboardReferralsPayoutRouteImport.update({
    id: '/payout',
    path: '/payout',
    getParentRoute: () => DashboardReferralsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/competition-rules': typeof CompetitionRulesRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/winners': typeof WinnersRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dashboard/competitions': typeof DashboardCompetitionsRoute
  '/dashboard/entries': typeof DashboardEntriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRouteWithChildren
  '/dashboard/reward-pool': typeof DashboardRewardPoolRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/draw-verification/$campaign': typeof DrawVerificationCampaignRoute
  '/draw-verification/$slug': typeof DrawVerificationSlugRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/listings': typeof PartnerListingsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/settlements': typeof PartnerSettlementsRoute
  '/partner/submit': typeof PartnerSubmitRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/dashboard/referrals/payout': typeof DashboardReferralsPayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/competition-rules': typeof CompetitionRulesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/winners': typeof WinnersRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dashboard/competitions': typeof DashboardCompetitionsRoute
  '/dashboard/entries': typeof DashboardEntriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRouteWithChildren
  '/dashboard/reward-pool': typeof DashboardRewardPoolRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/draw-verification/$campaign': typeof DrawVerificationCampaignRoute
  '/draw-verification/$slug': typeof DrawVerificationSlugRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/listings': typeof PartnerListingsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/settlements': typeof PartnerSettlementsRoute
  '/partner/submit': typeof PartnerSubmitRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin': typeof AdminIndexRoute
  '/competitions': typeof CompetitionsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/dashboard/referrals/payout': typeof DashboardReferralsPayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/competition-rules': typeof CompetitionRulesRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/winners': typeof WinnersRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/competitions': typeof AdminCompetitionsRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/users': typeof AdminUsersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dashboard/competitions': typeof DashboardCompetitionsRoute
  '/dashboard/entries': typeof DashboardEntriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRouteWithChildren
  '/dashboard/reward-pool': typeof DashboardRewardPoolRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/draw-verification/$campaign': typeof DrawVerificationCampaignRoute
  '/draw-verification/$slug': typeof DrawVerificationSlugRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/listings': typeof PartnerListingsRoute
  '/partner/profile': typeof PartnerProfileRoute
  '/partner/settlements': typeof PartnerSettlementsRoute
  '/partner/submit': typeof PartnerSubmitRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
  '/competitions/': typeof CompetitionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/dashboard/referrals/payout': typeof DashboardReferralsPayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/become-a-partner'
    | '/competition-rules'
    | '/competitions'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy-policy'
    | '/robots'
    | '/terms-and-conditions'
    | '/winners'
    | '/admin/audit-logs'
    | '/admin/competitions'
    | '/admin/config'
    | '/admin/fraud'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/users'
    | '/competitions/$slug'
    | '/dashboard/competitions'
    | '/dashboard/entries'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reward-pool'
    | '/dashboard/security'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/draw-verification/$campaign'
    | '/draw-verification/$slug'
    | '/partner/analytics'
    | '/partner/listings'
    | '/partner/profile'
    | '/partner/settlements'
    | '/partner/submit'
    | '/sitemap/xml'
    | '/admin/'
    | '/competitions/'
    | '/dashboard/'
    | '/partner/'
    | '/dashboard/referrals/payout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/become-a-partner'
    | '/competition-rules'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy-policy'
    | '/robots'
    | '/terms-and-conditions'
    | '/winners'
    | '/admin/audit-logs'
    | '/admin/competitions'
    | '/admin/config'
    | '/admin/fraud'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/users'
    | '/competitions/$slug'
    | '/dashboard/competitions'
    | '/dashboard/entries'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reward-pool'
    | '/dashboard/security'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/draw-verification/$campaign'
    | '/draw-verification/$slug'
    | '/partner/analytics'
    | '/partner/listings'
    | '/partner/profile'
    | '/partner/settlements'
    | '/partner/submit'
    | '/sitemap/xml'
    | '/admin'
    | '/competitions'
    | '/dashboard'
    | '/partner'
    | '/dashboard/referrals/payout'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/become-a-partner'
    | '/competition-rules'
    | '/competitions'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy-policy'
    | '/robots'
    | '/terms-and-conditions'
    | '/winners'
    | '/admin/audit-logs'
    | '/admin/competitions'
    | '/admin/config'
    | '/admin/fraud'
    | '/admin/notifications'
    | '/admin/partners'
    | '/admin/payouts'
    | '/admin/reports'
    | '/admin/users'
    | '/competitions/$slug'
    | '/dashboard/competitions'
    | '/dashboard/entries'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/reward-pool'
    | '/dashboard/security'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/draw-verification/$campaign'
    | '/draw-verification/$slug'
    | '/partner/analytics'
    | '/partner/listings'
    | '/partner/profile'
    | '/partner/settlements'
    | '/partner/submit'
    | '/sitemap/xml'
    | '/admin/'
    | '/competitions/'
    | '/dashboard/'
    | '/partner/'
    | '/dashboard/referrals/payout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BecomeAPartnerRoute: typeof BecomeAPartnerRoute
  CompetitionRulesRoute: typeof CompetitionRulesRoute
  CompetitionsRoute: typeof CompetitionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsRoute: typeof RobotsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WinnersRoute: typeof WinnersRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCompetitionsRoute: typeof AdminCompetitionsRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  DashboardCompetitionsRoute: typeof DashboardCompetitionsRoute
  DashboardEntriesRoute: typeof DashboardEntriesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRouteWithChildren
  DashboardRewardPoolRoute: typeof DashboardRewardPoolRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DrawVerificationCampaignRoute: typeof DrawVerificationCampaignRoute
  DrawVerificationSlugRoute: typeof DrawVerificationSlugRoute
  PartnerAnalyticsRoute: typeof PartnerAnalyticsRoute
  PartnerListingsRoute: typeof PartnerListingsRoute
  PartnerProfileRoute: typeof PartnerProfileRoute
  PartnerSettlementsRoute: typeof PartnerSettlementsRoute
  PartnerSubmitRoute: typeof PartnerSubmitRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner': {
      id: '/become-a-partner'
      path: '/become-a-partner'
      fullPath: '/become-a-partner'
      preLoaderRoute: typeof BecomeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition-rules': {
      id: '/competition-rules'
      path: '/competition-rules'
      fullPath: '/competition-rules'
      preLoaderRoute: typeof CompetitionRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots': {
      id: '/robots'
      path: '/robots'
      fullPath: '/robots'
      preLoaderRoute: typeof RobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/competitions': {
      id: '/admin/competitions'
      path: '/admin/competitions'
      fullPath: '/admin/competitions'
      preLoaderRoute: typeof AdminCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/admin/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/admin/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/': {
      id: '/competitions/'
      path: '/'
      fullPath: '/competitions/'
      preLoaderRoute: typeof CompetitionsIndexRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/competitions': {
      id: '/dashboard/competitions'
      path: '/dashboard/competitions'
      fullPath: '/dashboard/competitions'
      preLoaderRoute: typeof DashboardCompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/entries': {
      id: '/dashboard/entries'
      path: '/dashboard/entries'
      fullPath: '/dashboard/entries'
      preLoaderRoute: typeof DashboardEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/dashboard/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reward-pool': {
      id: '/dashboard/reward-pool'
      path: '/dashboard/reward-pool'
      fullPath: '/dashboard/reward-pool'
      preLoaderRoute: typeof DashboardRewardPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/dashboard/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw-verification/$campaign': {
      id: '/draw-verification/$campaign'
      path: '/draw-verification/$campaign'
      fullPath: '/draw-verification/$campaign'
      preLoaderRoute: typeof DrawVerificationCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw-verification/$slug': {
      id: '/draw-verification/$slug'
      path: '/draw-verification/$slug'
      fullPath: '/draw-verification/$slug'
      preLoaderRoute: typeof DrawVerificationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/analytics': {
      id: '/partner/analytics'
      path: '/partner/analytics'
      fullPath: '/partner/analytics'
      preLoaderRoute: typeof PartnerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/listings': {
      id: '/partner/listings'
      path: '/partner/listings'
      fullPath: '/partner/listings'
      preLoaderRoute: typeof PartnerListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/profile': {
      id: '/partner/profile'
      path: '/partner/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof PartnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/settlements': {
      id: '/partner/settlements'
      path: '/partner/settlements'
      fullPath: '/partner/settlements'
      preLoaderRoute: typeof PartnerSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/submit': {
      id: '/partner/submit'
      path: '/partner/submit'
      fullPath: '/partner/submit'
      preLoaderRoute: typeof PartnerSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/referrals/payout': {
      id: '/dashboard/referrals/payout'
      path: '/payout'
      fullPath: '/dashboard/referrals/payout'
      preLoaderRoute: typeof DashboardReferralsPayoutRouteImport
      parentRoute: typeof DashboardReferralsRoute
    }
  }
}

interface CompetitionsRouteChildren {
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  CompetitionsIndexRoute: typeof CompetitionsIndexRoute
}

const CompetitionsRouteChildren: CompetitionsRouteChildren = {
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  CompetitionsIndexRoute: CompetitionsIndexRoute,
}

const CompetitionsRouteWithChildren = CompetitionsRoute._addFileChildren(
  CompetitionsRouteChildren,
)

interface DashboardReferralsRouteChildren {
  DashboardReferralsPayoutRoute: typeof DashboardReferralsPayoutRoute
}

const DashboardReferralsRouteChildren: DashboardReferralsRouteChildren = {
  DashboardReferralsPayoutRoute: DashboardReferralsPayoutRoute,
}

const DashboardReferralsRouteWithChildren =
  DashboardReferralsRoute._addFileChildren(DashboardReferralsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BecomeAPartnerRoute: BecomeAPartnerRoute,
  CompetitionRulesRoute: CompetitionRulesRoute,
  CompetitionsRoute: CompetitionsRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsRoute: RobotsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WinnersRoute: WinnersRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCompetitionsRoute: AdminCompetitionsRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  DashboardCompetitionsRoute: DashboardCompetitionsRoute,
  DashboardEntriesRoute: DashboardEntriesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRouteWithChildren,
  DashboardRewardPoolRoute: DashboardRewardPoolRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DrawVerificationCampaignRoute: DrawVerificationCampaignRoute,
  DrawVerificationSlugRoute: DrawVerificationSlugRoute,
  PartnerAnalyticsRoute: PartnerAnalyticsRoute,
  PartnerListingsRoute: PartnerListingsRoute,
  PartnerProfileRoute: PartnerProfileRoute,
  PartnerSettlementsRoute: PartnerSettlementsRoute,
  PartnerSubmitRoute: PartnerSubmitRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
