/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeAPartnerRouteImport } from './routes/become-a-partner'
import { Route as CompetitionRulesRouteImport } from './routes/competition-rules'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RobotsRouteImport } from './routes/robots'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardEntriesRouteImport } from './routes/dashboard.entries'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard.security'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DrawVerificationCampaignRouteImport } from './routes/draw-verification.$campaign'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as DashboardReferralsPayoutRouteImport } from './routes/dashboard.referrals.payout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAPartnerRoute = BecomeAPartnerRouteImport.update({
  id: '/become-a-partner',
  path: '/become-a-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRulesRoute = CompetitionRulesRouteImport.update({
  id: '/competition-rules',
  path: '/competition-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsRoute = RobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CompetitionsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEntriesRoute = DashboardEntriesRouteImport.update({
  id: '/dashboard/entries',
  path: '/dashboard/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/dashboard/referrals',
  path: '/dashboard/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/dashboard/security',
  path: '/dashboard/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/dashboard/transactions',
  path: '/dashboard/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/dashboard/wallet',
  path: '/dashboard/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawVerificationCampaignRoute =
  DrawVerificationCampaignRouteImport.update({
    id: '/draw-verification/$campaign',
    path: '/draw-verification/$campaign',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReferralsPayoutRoute =
  DashboardReferralsPayoutRouteImport.update({
    id: '/payout',
    path: '/payout',
    getParentRoute: () => DashboardReferralsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/competition-rules': typeof CompetitionRulesRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/winners': typeof WinnersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dashboard/entries': typeof DashboardEntriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/draw-verification/$campaign': typeof DrawVerificationCampaignRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/referrals/payout': typeof DashboardReferralsPayoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/competition-rules': typeof CompetitionRulesRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/winners': typeof WinnersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dashboard/entries': typeof DashboardEntriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/draw-verification/$campaign': typeof DrawVerificationCampaignRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/referrals/payout': typeof DashboardReferralsPayoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/become-a-partner': typeof BecomeAPartnerRoute
  '/competition-rules': typeof CompetitionRulesRoute
  '/competitions': typeof CompetitionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/robots': typeof RobotsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/winners': typeof WinnersRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/dashboard/entries': typeof DashboardEntriesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/referrals': typeof DashboardReferralsRouteWithChildren
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/draw-verification/$campaign': typeof DrawVerificationCampaignRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/referrals/payout': typeof DashboardReferralsPayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/become-a-partner'
    | '/competition-rules'
    | '/competitions'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy-policy'
    | '/robots'
    | '/terms-and-conditions'
    | '/winners'
    | '/competitions/$slug'
    | '/dashboard/entries'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/security'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/draw-verification/$campaign'
    | '/sitemap/xml'
    | '/dashboard/'
    | '/dashboard/referrals/payout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/become-a-partner'
    | '/competition-rules'
    | '/competitions'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy-policy'
    | '/robots'
    | '/terms-and-conditions'
    | '/winners'
    | '/competitions/$slug'
    | '/dashboard/entries'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/security'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/draw-verification/$campaign'
    | '/sitemap/xml'
    | '/dashboard'
    | '/dashboard/referrals/payout'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/become-a-partner'
    | '/competition-rules'
    | '/competitions'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/privacy-policy'
    | '/robots'
    | '/terms-and-conditions'
    | '/winners'
    | '/competitions/$slug'
    | '/dashboard/entries'
    | '/dashboard/profile'
    | '/dashboard/referrals'
    | '/dashboard/security'
    | '/dashboard/transactions'
    | '/dashboard/wallet'
    | '/draw-verification/$campaign'
    | '/sitemap/xml'
    | '/dashboard/'
    | '/dashboard/referrals/payout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BecomeAPartnerRoute: typeof BecomeAPartnerRoute
  CompetitionRulesRoute: typeof CompetitionRulesRoute
  CompetitionsRoute: typeof CompetitionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsRoute: typeof RobotsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WinnersRoute: typeof WinnersRoute
  DashboardEntriesRoute: typeof DashboardEntriesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReferralsRoute: typeof DashboardReferralsRouteWithChildren
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DrawVerificationCampaignRoute: typeof DrawVerificationCampaignRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-partner': {
      id: '/become-a-partner'
      path: '/become-a-partner'
      fullPath: '/become-a-partner'
      preLoaderRoute: typeof BecomeAPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition-rules': {
      id: '/competition-rules'
      path: '/competition-rules'
      fullPath: '/competition-rules'
      preLoaderRoute: typeof CompetitionRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots': {
      id: '/robots'
      path: '/robots'
      fullPath: '/robots'
      preLoaderRoute: typeof RobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof CompetitionsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/entries': {
      id: '/dashboard/entries'
      path: '/dashboard/entries'
      fullPath: '/dashboard/entries'
      preLoaderRoute: typeof DashboardEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/dashboard/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/dashboard/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/dashboard/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw-verification/$campaign': {
      id: '/draw-verification/$campaign'
      path: '/draw-verification/$campaign'
      fullPath: '/draw-verification/$campaign'
      preLoaderRoute: typeof DrawVerificationCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/referrals/payout': {
      id: '/dashboard/referrals/payout'
      path: '/payout'
      fullPath: '/dashboard/referrals/payout'
      preLoaderRoute: typeof DashboardReferralsPayoutRouteImport
      parentRoute: typeof DashboardReferralsRoute
    }
  }
}

interface CompetitionsRouteChildren {
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
}

const CompetitionsRouteChildren: CompetitionsRouteChildren = {
  CompetitionsSlugRoute: CompetitionsSlugRoute,
}

const CompetitionsRouteWithChildren = CompetitionsRoute._addFileChildren(
  CompetitionsRouteChildren,
)

interface DashboardReferralsRouteChildren {
  DashboardReferralsPayoutRoute: typeof DashboardReferralsPayoutRoute
}

const DashboardReferralsRouteChildren: DashboardReferralsRouteChildren = {
  DashboardReferralsPayoutRoute: DashboardReferralsPayoutRoute,
}

const DashboardReferralsRouteWithChildren =
  DashboardReferralsRoute._addFileChildren(DashboardReferralsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BecomeAPartnerRoute: BecomeAPartnerRoute,
  CompetitionRulesRoute: CompetitionRulesRoute,
  CompetitionsRoute: CompetitionsRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsRoute: RobotsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WinnersRoute: WinnersRoute,
  DashboardEntriesRoute: DashboardEntriesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReferralsRoute: DashboardReferralsRouteWithChildren,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DrawVerificationCampaignRoute: DrawVerificationCampaignRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
